
language: java
sudo: false

jdk:
  - openjdk9
  
git:
  submodules: false

install: true
script: "mvn clean install"
matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/maven'

before_cache:
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false

deploy:
- provider: releases
  prerelease: true
  api_key: "$API_KEY"
  file_glob: true
  file:
  - esql-plugin/target/sonar-msgflow-plugin-*.jar
  skip_cleanup: true
  on:
    tags: true
